name: by_arena
description: BY ARENA - Tienda de joyerÃ­a y accesorios premium
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  dio: ^5.4.0
  go_router: ^13.2.0
  cached_network_image: ^3.3.1
  flutter_secure_storage: ^9.0.0
  google_fonts: ^6.1.0
  shimmer: ^3.0.0
  intl: ^0.19.0
  url_launcher: ^6.2.4
  flutter_stripe: ^10.1.1
  share_plus: ^7.2.2
  badges: ^3.1.2
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.9

flutter:
  uses-material-design: true

  assets:
    - assets/images/
